export const ROUTES = {
    HOME: '/',
    NEW_POST: '/new-post',
    YOUR_POSTS: '/your-posts',
    ABOUT_US: '/about-us',
    CONTACT: '/contact',
    LEAVE_COMMENT: '/leave-comment',
    LOGIN: '/login',
    LOGOUT: '/logout',
    REGISTER: '/register',
    ADMIN_PAGE: '/admin',
    ADMIN_USERS: '/admin/users',
    ADMIN_POSTS: '/admin/posts',
    ADMIN_COMMENTS: '/admin/comments',
};